
info:
  description: Football Match Engine

server:
  port: 8080

spring:
  application:
    name: football-engine

logging:
  structured:
    # This toggles JSON logging. Options: logstash, ecs (Elastic), gelf
    format:
      console: logstash
  level:
    root: INFO
    com.example: DEBUG



springdoc:
  swagger-ui:
    operationsSorter: method
    groups-order: asc

gnovoab:
  openapi:
    dev-url: "http://localhost:8080"
    prod-url: "https://gnovoab-api.com"


management:
  otlp:
    metrics:
      export:
        enabled: false
    logging:
        export:
          enabled: false
    tracing:
      # Automatically correlates logs with Trace IDs
      endpoint: http://localhost:4318/v1/traces
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health,info"
    jmx:
      exposure:
        include: "health,info"

sim:
  tickMillis: 250
  snapshotEverySeconds: 10
  halfTimeRealSeconds: 30
  rosters:
    baseDir: "./rosters"
    files:
      PREMIER_LEAGUE: "premier-league.json"
      SERIE_A: "serie-a.json"
      LA_LIGA: "la-liga.json"

runner:
  seasonsToRun: 2
  gapBetweenFixturesMinutes: 10
  gapBetweenSeasonsMinutes: 60
  autoStartOnBoot: true